services:
  backend:
    working_dir: /backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "50051:50051"
    networks:
      - sample-bff
    tty: true
  bff:
    working_dir: /bff
    build:
      context: .
      dockerfile: Dockerfile.bff
    ports:
      - "8080:8080"
    networks:
      - sample-bff
    depends_on:
      - backend
    tty: true
    extra_hosts:
      - host.docker.internal:host-gateway
  frontend:
    working_dir: /app
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    networks:
      - sample-bff
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
networks:
  sample-bff:
volumes:
  node_modules:
