FROM node:22-slim AS base

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

WORKDIR /app

COPY ./frontend/package.json /app
RUN corepack enable

RUN pnpm install
RUN pnpm update

RUN mkdir node_modules/.cache && chmod -R 777 node_modules/.cache

COPY ./frontend /app

EXPOSE 5173

CMD ["pnpm", "run", "dev"]
